# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kangfoo
tagline:          A daily iteration
url:              https://kangfoo.com
paginate:         1
baseurl:          /
author:
  name:           Kangfoo
  url:            https://kangfoo.com
  email:          kangfoo2@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/kangfoo2
