# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kangfoo
tagline:          A daily iteration
url:              http://kangfoo.com
paginate:         5
baseurl:          /
author:
  name:           Kangfoo2
  url:            https://twitter.com/kangfoo2
  email:          kangfoo2@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/kangfoo2
